### ISSUE TITLE
Problems with neofetch

### ISSUE THREAD

**Issue by hackerncoder** [Dko1905/uwufy#1]
See title.
Wont ever be using it again, is really bad.

**Comment by dko1905** [comment]
The neofetch glitch was fixed in commit [83831197e23b320037dac09fcc32711129592c23](https://github.com/Dko1905/uwufy/commit/83831197e23b320037dac09fcc32711129592c23) and a newly discovered htop glitch was fixed in [9c24baea3715851bdb58c1dc3606473483a38b3c](https://github.com/Dko1905/uwufy/commit/9c24baea3715851bdb58c1dc3606473483a38b3c).

The fixes are not yet released for .deb and .rpm packages.
